### PR TITLE
Kitsunenosara t chapters

### PR DESCRIPTION
**Pull request by kitsunenosaraT**
Create new folder whit separate files for each chapter of the guide.
See each file for a description of the relative chapter.

### CODE REVIEW

**Comment by kitsunenosaraT** [comment]
The Chapters folder contains one dedicated file for each chapter of the guide. See each file for the chapter descriptiom

**Comment by gialloporpora** [comment]
I think we could start assigning chapters and work on them.

**Comment by kitsunenosaraT** [comment]
Thank you for anticipating me :grin:
I think the more pressing ones are **chapter 3 and 4**.
You wrote the majority of the source material about file types and are more knowledgeable than me on the topic, while I've been going through the workflow many times recently with eliogi… How about you take chapter 4 and I chapter 3?

But before that, I would like to give priority to the Code of Conduct  (for you) and the Contributing (for me) files, since in today's Call I was said that we need them as soon as possible in order to register the project to the Global Sprint.

**Comment by gialloporpora** [comment]
OK, I focus myself on the code of conduct  this week and on chapter 3 
and 4 the next one.

**Comment by eliogi** [comment]
Hi everybody,
please, tell me how I could support you.
I've already finished my answers to the survey.

**Comment by kitsunenosaraT** [comment]
@eliogi Wow, thank you for going through the survey!
Can you please copy your answer in the comment section of Issue #7 I think it will be easier for new contributors to write after reading your example.

About the guide, please don't feel left out if I didn't assign you any chapter yet. 
At this stage (first draft) we need more than ever an external point of view to point out the shortcomings in our method, if it does make sense.
As the most recent team member and junior translator you are in a unique position to review the first draft and detect the weakest parts, so I need you to keep your distance so that you will see the guide with a fresh mind.

Of course things will change radically with the second draft: you will be able actively involved in the rewriting of the final guide and will also be encourage to add parts of your own.
So, please, have still a little patience 😉

**Comment by eliogi** [comment]
@kitsunenosaraT hi Sara, I've done the task you suggested me. I've copied my comment at the end of the thread of issue #7 .
Don't worry for me it's ok. I didn't know exactly how to proceed; so now it's all clear and I agree with the methodology adopted by you. 
So... let's good.
I'm available for cooperation when you need me.

**Pull request merged**
