### PR TITLE
Markdown style fixes + .gitignore

### PR DESCRIPTION
**Pull request by flodolo**
While snooping into the repository I noticed `.DS_Store` files committed. You should not have that: the first commit takes care of removing the existing files, and adding the pattern to `.gitignore`.

The second problem is defining some ground rules on how to write markdown files. You can see an [example here](https://github.com/mozilla-l10n/documentation/blob/master/misc/documentation_styleguide.md), and even instructions on how to run an automated linter on pull requests.

I strongly suggest to use Atom to work on markdown files. You have a preview, nice syntax highlighting, and you would get rid of all the trailing white spaces.

The only file heavily edited is `resources/regole_traduzione.md`: you should remove unnecessary empty lines, and use titles, not bold text. I assume that content was converted/copied from the original page on the website.

Last note: when merging a pull request, you can "merge the pull request", or "squash the commits". The latter creates a much cleaner history, and you can even set it as default in the repository's settings.

### CODE REVIEW

**Comment by flodolo** [comment]
Note: I can drop the white spaces changes and only fix `.gitignore` + `resources/regole_traduzione.md` if you prefer.

**Comment by kitsunenosaraT** [comment]
@flodolo Thank you so much for having a look at the repo and taking care of that .DS_store, also for explainig to me the *squash the commit* command. I had a lot of reserves making small commits because they clogged up the repo history. It's nice to know that I have this option.

As you guessed, resources/regole_traduzione.md was dropped in the repo without much tought for mardown, because it's not part of the official documentation, more like a memo. But thanks, it's nice to have it properly formatted.

I already read the [style guide](https://github.com/mozilla-l10n/documentation/blob/master/misc/documentation_styleguide.md) previously and intended to propose other contributors to adopt it, since we lack a guide of our own.

I already use Atom to edit files, but I have just one doubt regarding trailing spaces...
The double white space at the end of sentences is meant to display a breakline. I already discussed with @gialloporpora how to have breaklines properly displayed on GitBooks (where the public version of the guide will be hosted), and trailing double spaces seem to be the only thing that works. Do you have a more effective alternative?

**Comment by flodolo** [comment]
> The double white space at the end of sentences is meant to display a breakline. I already discussed with @gialloporpora how to have breaklines properly displayed on GitBooks (where the public version of the guide will be hosted), and trailing double spaces seem to be the only thing that works. Do you have a more effective alternative?

The only place where white spaces are relevant should be code fences. What do you mean with line breaking? Have an example?

**Comment by flodolo** [comment]
Ugh, I'm seeing it now (line break within a paragraph). This is ugly.

**Comment by kitsunenosaraT** [comment]
Linebreak like the markdown counterpart of  the `<br>` tag, that is, starting a new line without starting a new paragraph.

e.g.

Firefox is brought you by Mozilla. `linebreak`
Download the lastest version below.

**Comment by flodolo** [comment]
Updated. Technically, it should be possible to use a backslash, but Atom's preview fails, and I have no idea if it would work in Gitbook.
https://github.github.com/gfm/#example-630

I would question if you really need also those line breaks though, and you shouldn't be using a different semantic structure in most cases.

**Comment by kitsunenosaraT** [comment]
We already tried backslash, sadly it doesn't work either. The backslash is displayed as a normal character, instead of wrapping text.
As to if breaklines are really necessary... well, they are not instrumental, but surely they make things easier on the eye.
If they cause too much trouble we can drop them though. I can merge your pull and then make the necessary fixes to lines that need to be wrapped (shouldn't be to many).

**Comment by flodolo** [comment]
> As to if breaklines are really necessary... well, they are not instrumental, but surely they make things easier on the eye.

To be honest, for those cases I would use `<br>` to avoid any confusion, assuming that works in GitBook as well. But that's matter for a different discussion.

Also meh, GFM seems to actually not be used in GH
https://stackoverflow.com/questions/18019957/where-is-github-flavored-markdown-gfm-actually-used-in-github

**Comment by kitsunenosaraT** [comment]
@gialloporpora (sorry I keep pinging you today 😅 ) What do you think of this pull proposed by flodolo?
If I remember correctly, you had some reserves about using `<br>` tags in markdown.

Also, since at some point we talked about writing an instruction file on markdown formatting for our repo, how about basing it on [this one](https://github.com/mozilla-l10n/documentation/blob/master/misc/documentation_styleguide.md) of [mozilla-l10n](https://github.com/mozilla-l10n)?

**Comment by kitsunenosaraT** [comment]
Thank you @flodolo for the fixes 👍

**Pull request merged**
